version: "3.3"
services:
  spark-master:
    image: tw5831/dataengineering1:cluster-apache-spark
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/usr/local/spark-apps
       - ./data:/usr/local/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: tw5831/dataengineering1:cluster-apache-spark
    ports:
      - "9091:8080"
      - "7000:7000"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/usr/local/spark-apps
       - ./data:/usr/local/spark-data
    depends_on:
      - spark-master
  spark-worker-b:
    image: tw5831/dataengineering1:cluster-apache-spark
    ports:
      - "9092:8080"
      - "7001:7000"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/usr/local/spark-apps
        - ./data:/usr/local/spark-data
    depends_on:
      - spark-master
